# Generated by Django 3.2.8 on 2021-11-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_auto_20211125_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='semester',
            new_name='semeseter',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semseter',
            new_name='semeseter',
        ),
    ]
