# Generated by Django 3.2.8 on 2021-11-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_auto_20211125_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='semeseter',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semeseter',
            new_name='semester',
        ),
    ]
