# Generated by Django 3.2.8 on 2021-11-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_auto_20211125_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudents',
            name='studentid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='classstudents',
            unique_together={('studentid', 'Class')},
        ),
    ]
