# Generated by Django 3.2.8 on 2021-11-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0006_auto_20211126_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
