# Generated by Django 3.2.8 on 2021-12-07 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0009_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudents',
            name='studentid',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
