# Generated by Django 3.2.8 on 2022-01-16 19:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_app', '0010_alter_classstudents_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)])),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.class')),
                ('Ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
