# Generated by Django 3.2 on 2021-11-03 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=600, null=True)),
                ('password', models.CharField(max_length=6, null=True)),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=10)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_owner', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='class_student', to=settings.AUTH_USER_MODEL)),
                ('tas', models.ManyToManyField(related_name='class_ta', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_university', to='class.university')),
            ],
        ),
    ]
