# Generated by Django 3.2.8 on 2021-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(max_length=30),
        ),
    ]
