# Generated by Django 3.2.8 on 2021-11-16 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0004_alter_class_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='headta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_headta', to=settings.AUTH_USER_MODEL),
        ),
    ]
