# Generated by Django 3.2.8 on 2021-10-28 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211023_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter.', regex='^(?=.*[A-Z])'), django.core.validators.RegexValidator(message='Password must contain at least one number.', regex='^(?=.*[0-9])'), django.core.validators.RegexValidator(message='Password must be eight characters or longer.', regex='^(?=.{8,})')]),
        ),
    ]
