# Generated by Django 3.2.8 on 2021-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211103_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
