# Generated by Django 3.2.8 on 2021-11-18 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_app', '0002_auto_20211118_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='atend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('session_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_session', to='class_app.class')),
                ('students', models.ManyToManyField(related_name='user_session', through='attendance.atend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atend',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.session'),
        ),
        migrations.AddField(
            model_name='atend',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
