# Generated by Django 3.2.8 on 2021-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atend',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='students',
        ),
        migrations.AddField(
            model_name='session',
            name='atends',
            field=models.ManyToManyField(related_name='user_session', to='attendance.atend'),
        ),
    ]
