# Generated by Django 3.2.8 on 2021-11-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_auto_20211118_1342'),
        ('attendance', '0002_auto_20211118_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_session', to='class_app.class'),
        ),
    ]
