# Generated by Django 3.2.8 on 2021-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_session_session_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atend',
            old_name='students',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='atend',
            name='Present',
            field=models.BooleanField(null=True),
        ),
    ]
