# Generated by Django 3.2.8 on 2021-12-15 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20211215_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 12, 15, 20, 23, 59, 19165)),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
