# Generated by Django 3.2.8 on 2021-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20211215_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
