# Generated by Django 3.2.8 on 2021-12-15 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20211215_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 12, 15, 21, 47, 40, 65283)),
        ),
    ]
