# Generated by Django 3.2.8 on 2022-01-16 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 17, 0, 32, 18, 447772)),
        ),
    ]
