# Generated by Django 3.2.8 on 2022-01-17 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 17, 18, 38, 27, 61029)),
        ),
    ]
