# Generated by Django 3.2.8 on 2022-01-20 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 20, 21, 21, 31, 623130)),
        ),
    ]
