# Generated by Django 3.2.8 on 2022-01-23 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 23, 14, 54, 6, 118201)),
        ),
    ]
