# Generated by Django 3.2.8 on 2021-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
