# Generated by Django 3.2.8 on 2021-11-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='class_id',
            new_name='class_fk',
        ),
    ]
