# Generated by Django 3.2.8 on 2021-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='avg_grade',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_grade',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='assignment',
            name='min_grade',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='avg_grade',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='max_grade',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='min_grade',
            field=models.FloatField(default=None),
        ),
    ]
