# Generated by Django 3.2.8 on 2021-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_auto_20211118_1342'),
        ('assignment', '0002_rename_class_id_assignment_class_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('name', 'class_fk')},
        ),
    ]
