# Generated by Django 3.2.8 on 2021-12-06 10:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_app', '0009_alter_class_name'),
        ('assignment', '0003_auto_20211203_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_graded',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_graded',
        ),
        migrations.RemoveField(
            model_name='question',
            name='weight',
        ),
        migrations.AddField(
            model_name='assignment',
            name='not_graded_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='full_grade',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='not_graded_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('class_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_grade', to='class_app.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class_grade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
