# Generated by Django 3.2.8 on 2021-12-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20211206_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
