# Generated by Django 3.2.8 on 2021-12-07 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20211206_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='full_grade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
