# Generated by Django 3.2.8 on 2021-12-07 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20211207_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
