# Generated by Django 3.2.8 on 2021-12-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_alter_assignment_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_graded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='not_graded_count',
            field=models.IntegerField(default=0),
        ),
    ]
