# Generated by Django 3.2.8 on 2021-12-08 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20211207_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
