# Generated by Django 3.2.8 on 2021-12-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0009_alter_class_name'),
        ('assignment', '0009_alter_grade_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='class_fk',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='assignmentgrade',
            old_name='assignment',
            new_name='assignment_id',
        ),
        migrations.RenameField(
            model_name='assignmentgrade',
            old_name='student',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='classgrade',
            old_name='class_fk',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='classgrade',
            old_name='student',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='student',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='assignment_fk',
            new_name='assignment_id',
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('name', 'class_id')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('name', 'assignment_id')},
        ),
    ]
