# Generated by Django 3.2.8 on 2021-12-09 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20211209_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
