# Generated by Django 3.2.8 on 2021-12-09 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_alter_grade_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='delay',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
