# Generated by Django 3.2.8 on 2021-12-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_alter_grade_delay'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
    ]
